(deftheme omarchy
  "Created 2023-05-27.")

(defun jake-interpolate-color (color1 color2 ratio)
  "Interpolate between COLOR1 and COLOR2 by RATIO."
  (let* ((c1 (color-name-to-rgb color1))
         (c2 (color-name-to-rgb color2))
         (red   (+ (* (- (nth 0 c2) (nth 0 c1)) ratio) (nth 0 c1)))
         (green (+ (* (- (nth 1 c2) (nth 1 c1)) ratio) (nth 1 c1)))
         (blue  (+ (* (- (nth 2 c2) (nth 2 c1)) ratio) (nth 2 c1))))
    (apply 'color-rgb-to-hex (list red green blue))))


(defvar jake-pink "#fc199a")
(defvar jake-yellow "#fad000")
(defvar jake-dark "#200933")
(defvar jake-darkest "#1D0432")
(defvar jake-green "#a5ff90")
(defvar jake-cyan "#61e2ff")
(defvar jake-cyan-highlight "#9EFFFF")
(defvar jake-purple-dark "#371057")
(defvar jake-purple "#9963ff")
(defvar jake-purple-subtle "#574497")

(let ((jake-fixed "MonaspiceAr NFM")
      (jake-variable "Noto Sans")
      (jake-variable-heading "MonaspiceRn Nerd Font")
      (jake-script "MonaspiceRn Nerd Font")

      (jake-normal-weight 'light)

      (jake-org-2 (jake-interpolate-color jake-yellow jake-cyan 0.0))
      (jake-org-3 (jake-interpolate-color jake-yellow jake-cyan 0.3))
      (jake-org-4 (jake-interpolate-color jake-yellow jake-cyan 0.6))
      (jake-org-5 (jake-interpolate-color jake-yellow jake-cyan 0.7))
      (jake-org-6 (jake-interpolate-color jake-yellow jake-cyan 0.8))
      (jake-org-7 (jake-interpolate-color jake-yellow jake-cyan 0.9))
      (jake-org-8 (jake-interpolate-color jake-yellow jake-cyan 0.95)))


  (defface jake-script `((t (:family ,jake-script))) "jakewave script face.")
  (defface jake-highlight `((t (:background ,jake-purple-dark))) "jakewave dark purple")

  (defface jake-no-glow `((t)) "jakewave non glowing face.")

  (defface jake-cyan `((t (:foreground ,jake-cyan))) "jakewave non glowing cyan face.")
  (defface jake-cyan-highlight `((t (:foreground ,jake-cyan-highlight))) "jakewave non glowing cyan highlight face.")
  (defface jake-yellow `((t (:foreground ,jake-yellow))) "jakewave non glowing yellow face.")
  (defface jake-green `((t (:foreground ,jake-green))) "jakewave non glowing green face.")
  (defface jake-pink `((t (:foreground ,jake-pink))) "jakewave non glowing pink face.")
  (defface jake-purple `((t (:foreground ,jake-purple))) "jakewave non glowing purple face.")
  (defface jake-purple-subtle `((t (:foreground ,jake-purple-subtle))) "jakewave non glowing purple-subtle face.")

  (defface jake-cyan-glow `((t (:foreground ,jake-cyan))) "jakewave glowing cyan face.")
  (defface jake-cyan-highlight-glow `((t (:foreground ,jake-cyan-highlight))) "jakewave glowing cyan face.")
  (defface jake-yellow-glow `((t (:foreground ,jake-yellow))) "jakewave glowing yellow face.")
  (defface jake-green-glow `((t (:foreground ,jake-green))) "jakewave glowing green face.")
  (defface jake-pink-glow `((t (:foreground ,jake-pink))) "jakewave glowing pink face.")
  (defface jake-purple-glow `((t (:foreground ,jake-purple))) "jakewave glowing purple face.")
  (defface jake-purple-subtle-glow `((t (:foreground ,jake-purple-subtle))) "jakewave glowing purple-subtle face.")

  (custom-theme-set-faces
   'omarchy

   `(ansi-color-bright-red ((t (:foreground ,jake-pink :background ,jake-pink))))
   `(ansi-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(ansi-color-red ((t (:foreground ,jake-pink :background ,jake-pink))))
   `(ansi-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(avy-background-face ((t (:inherit jake-no-glow :foreground ,jake-cyan :background ,jake-dark))))
   `(avy-lead-face ((t (:inherit (jake-pink-glow bold) :foreground unspecified :background ,jake-dark))))
   `(avy-lead-face-0 ((t (:inherit (jake-yellow-glow avy-lead-face) :foreground unspecified :background ,jake-dark))))
   `(avy-lead-face-1 ((t (:inherit (jake-green-glow avy-lead-face) :foreground unspecified :background ,jake-dark))))
   `(avy-lead-face-2 ((t (:inherit (jake-purple-glow avy-lead-face) :foreground unspecified :background ,jake-dark))))
   `(bold ((t (:weight normal))))
   `(button ((t (:inherit (link)))))
   `(calendar-today ((t (:inherit jake-green-glow :foreground unspecified))))
   `(calendar-weekday-header ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(calendar-weekend-header ((t (:inherit calendar-weekday-header :foreground unspecified))))
   `(company-preview ((t :inherit (jake-highlight jake-purple-subtle-glow) :foreground unspecified :background unspecified)))
   `(company-tooltip ((t :inherit jake-highlight :foreground ,jake-cyan :background unspecified)))
   `(company-tooltip-annotation ((t :inherit jake-yellow :foreground unspecified :background unspecified)))
   `(company-tooltip-annotation-selection ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(company-tooltip-common ((t :inherit jake-green :foreground unspecified :background unspecified)))
   `(company-tooltip-common-selection ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(company-tooltip-selection ((t :inherit (bold jake-cyan-glow) :foreground unspecified :background unspecified)))
   `(compilation-mode-line-fail ((t (:foreground ,jake-pink))))
   `(completions-annotations ((t :inherit (jake-purple jake-script) :foreground unspecified)))
   `(consult-file ((t :inherit jake-cyan :foreground unspecified :weight ,jake-normal-weight)))
   `(consult-help ((t :inherit jake-purple :foreground unspecified)))
   `(consult-highlight-match ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(consult-line-number ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(cursor ((t (:background ,jake-pink))))
   `(default ((t (:inherit nil :family ,jake-fixed :stipple nil :background ,jake-dark :foreground ,jake-cyan :inverse-video nil :box nil :strike-through nil :extend nil :overline nil :underline nil :shadow nil :slant normal :weight light :width normal :foundry "nil"))))
   `(diff-added ((t (:foreground ,jake-green))))
   `(diff-context ((t (:foreground ,jake-purple-subtle))))
   `(diff-hl-change ((t (:background ,jake-yellow :foreground ,jake-darkest))))
   `(diff-hl-delete ((t (:background ,jake-pink :foreground ,jake-darkest))))
   `(diff-hl-insert ((t (:background ,jake-green :foreground ,jake-darkest))))
   `(diff-removed ((t (:foreground ,jake-pink))))
   `(dired-directory ((t (:inherit (font-lock-constant-face) :foreground unspecified :background unspecified))))
   `(diredfl-compressed-file-suffix ((t (:inherit jake-green-glow))))
   `(diredfl-date-time ((t (:inherit jake-purple-glow))))
   `(diredfl-deletion ((t (:inherit (jake-pink-glow bold) :foreground unspecified :background unspecified))))
   `(diredfl-deletion-file-name ((t (:inherit jake-purple-subtle-glow :foreground unspecified))))
   `(diredfl-dir-heading ((t (:inherit jake-pink-glow))))
   `(diredfl-dir-name ((t (:inherit jake-pink-glow))))
   `(diredfl-dir-priv ((t (:inherit jake-yellow-glow))))
   `(diredfl-exec-priv ((t (:inherit jake-purple-glow))))
   `(diredfl-file-name ((t (:inherit (jake-yellow-glow)))))
   `(diredfl-file-suffix ((t (:inherit (jake-green-glow)))))
   `(diredfl-ignored-file-name ((t (:inherit jake-purple-subtle-glow))))
   `(diredfl-link-priv ((t (:inherit jake-yellow-glow))))
   `(diredfl-no-priv ((t (:inherit jake-purple-subtle-glow))))
   `(diredfl-number ((t (:inherit jake-yellow-glow))))
   `(diredfl-read-priv ((t (:inherit jake-green-glow))))
   `(diredfl-symlink ((t (:inherit jake-purple-glow))))
   `(diredfl-write-priv ((t (:inherit jake-pink-glow))))
   `(doom-modeline-bar ((t (:background ,jake-purple))))
   `(doom-modeline-bar-inactive ((t (:background ,jake-purple-dark))))
   `(doom-modeline-buffer-file ((t (:inherit jake-green-glow :foreground unspecified))))
   `(doom-modeline-buffer-modified ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(doom-modeline-error ((t (:inherit jake-pink))))
   `(doom-modeline-evil-insert-state ((t (:inherit jake-purple))))
   `(doom-modeline-evil-motion-state ((t (:inherit jake-cyan))))
   `(doom-modeline-evil-normal-state ((t (:inherit jake-green))))
   `(doom-modeline-info ((t (:inherit jake-green-glow :foreground unspecified))))
   `(doom-modeline-project-dir ((t (:inherit jake-purple-glow :foreground unspecified))))
   `(doom-modeline-warning ((t (:inherit jake-yellow))))
   `(error ((t (:foreground ,jake-pink))))
   `(escape-glyph ((t (:foreground "#9EFFFF"))))
   `(evil-ex-lazy-highlight ((t (:inherit (jake-no-glow bold) :foreground ,jake-dark :background ,jake-green))))
   `(fixed-pitch ((t (:family ,jake-fixed))))
   `(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face :foreground unspecified))))
   `(font-lock-builtin-face ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(font-lock-comment-delimiter-face ((default (:inherit font-lock-comment-face))))
   `(font-lock-comment-face ((t (:inherit (jake-script jake-purple-subtle-glow) :foreground unspecified :background unspecified))))
   `(font-lock-constant-face ((t (:foreground ,jake-purple))))
   `(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
   `(font-lock-doc-face ((t (:inherit (jake-script jake-purple-glow) :foreground unspecified))))
   `(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
   `(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
   `(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
   `(font-lock-function-name-face ((t (:inherit (jake-yellow-glow bold) :foreground unspecified))))
   `(font-lock-keyword-face ((t (:inherit (jake-pink-glow bold) :foreground unspecified :slant normal))))
   `(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face) :foreground unspecified))))
   `(font-lock-negation-char-face ((t (:foreground "#a45bad"))))
   `(font-lock-number-face ((t nil)))
   `(font-lock-operator-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(font-lock-preprocessor-face ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
   `(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
   `(font-lock-punctuation-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(font-lock-punctuation-face ((t nil)))
   `(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
   `(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
   `(font-lock-string-face ((t (:inherit jake-green-glow :foreground unspecified))))
   `(font-lock-type-face ((t (:inherit (jake-yellow-glow bold) :foreground unspecified))))
   `(font-lock-variable-name-face ((t (:inherit (jake-cyan-glow bold) :foreground unspecified))))
   `(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
   `(font-lock-warning-face ((t (:foreground "#dc752f" :background "#292b2e"))))
   `(fringe ((t (:background "#1d0432" :foreground "#520c8b"))))
   `(git-commit-keyword ((t (:inherit jake-no-glow))))
   `(gnus-header-content ((t (:foreground ,jake-purple))))
   `(gnus-header-from ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(gnus-header-name ((t (:foreground ,jake-pink))))
   `(gnus-header-subject ((t (:inherit jake-green-glow :foreground unspecified))))
   `(header-line ((t (:background ,jake-purple-dark :overline ,jake-purple))))
   `(helm-M-x-key ((t :inherit jake-green-glow :foreground unspecified :box t)))
   `(helm-command-active-mode ((t :inherit jake-yellow-glow :foreground unspecified)))
   `(helm-ff-directory ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-ff-dotted-symlink-direcroty ((t :inherit jake-purple-glow :foreground unspecified :background unspecified)))
   `(helm-ff-executable ((t :inherit jake-green :foreground unspecified :background unspecified)))
   `(helm-ff-file ((t :inherit jake-cyan :weight ,jake-normal-weight :foreground unspecified :background unspecified)))
   `(helm-ff-file-extension ((t :inherit jake-cyan-glow :foreground unspecified :background unspecified)))
   `(helm-ff-symlink ((t :inherit jake-purple :foreground unspecified :background unspecified)))
   `(helm-grep-lineno ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-match ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(helm-match-item ((t (:inherit (jake-no-glow bold) :foreground ,jake-dark :background ,jake-green))))
   `(helm-moccur-buffer ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(helm-posframe-border ((t :background ,jake-yellow)))
   `(helm-selection ((t :inherit jake-highlight :background unspecified)))
   `(helm-selection-line ((t :inherit jake-highlight :background unspecified)))
   `(helm-source-header ((t :inherit (jake-script jake-pink-glow) :foreground unspecified :background unspecified :underline ,jake-pink)))
   `(highlight ((t (:foreground unspecified :background unspecified))))
   `(highlight-parentheses-highlight ((t (:inherit bold))))
   `(hl-line ((t (:background ,jake-purple-dark))))
   `(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
   `(info-double-quoted-name ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(info-glossary-word ((t (:inherit link :foreground unspecified :underline t :box unspecified))))
   `(info-header-node ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(info-header-xref ((t (:inherit jake-pink-glow :foreground unspecified))))
   `(info-menu-header ((t (:inherit (variable-pitch jake-yellow bold) :foreground unspecified :weight normal))))
   `(info-quoted-name ((t (:inherit (jake-yellow-glow fixed-pitch) :foreground unspecified :background ,jake-purple-dark))))
   `(info-string ((t (:inherit jake-green-glow :foreground unspecified))))
   `(info-xref ((t (:inherit link :foreground unspecified :underline t))))
   `(info-xref-visited ((t (:inherit jake-purple-glow :foreground unspecified :underline t))))
   `(isearch ((t (:foreground "#2D2B55" :background "#FF7300"))))
   `(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
   `(js2-external-variable ((t (:foreground unspecified))))
   `(js2-function-param ((t (:inherit font-lock-constant-face :foreground unspecified))))
   `(lazy-highlight ((t (:weight normal :background "#FFFF03" :inherit (isearch)))))
   `(line-number ((t (:inherit (fixed-pitch) :background ,jake-darkest :foreground "#4A1E64"))))
   `(line-number-current-line ((t (:inherit bold :background ,jake-darkest :foreground "#7912CE" :weight unspecified))))
   `(link ((t (:inherit jake-cyan-highlight-glow :underline (:color foreground-color :style line :position nil) :foreground unspecified))))
   `(link-visited ((t (:underline (:color foreground-color :style line :position nil) :foreground "#c56ec3"))))
   `(lsp-flycheck-error-unnecessary-face ((t (:inherit jake-purple-subtle-glow :foreground unspecified))))
   `(lsp-flycheck-info-unnecessary-face ((t (:inherit jake-purple-subtle-glow :foreground unspecified))))
   `(lsp-flycheck-warning-unnecessary-face ((t (:inherit jake-purple-subtle-glow :foreground unspecified))))
   `(lsp-headerline-breadcrumb-path-face ((t (:inherit (font-lock-constant-face)))))
   `(lsp-headerline-breadcrumb-symbols-face ((t (:inherit (font-lock-type-face)))))
   `(lsp-ui-doc-background ((t :background ,jake-dark)))
   `(lsp-ui-peek-filename ((t :inherit jake-pink-glow :foreground unspecified)))
   `(lsp-ui-peek-footer ((t :inherit lsp-ui-peek-header :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-header ((t :inherit (header-line jake-yellow-glow) :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-highlight ((t :inherit (jake-green-glow bold) :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-list ((t :background unspecified :foreground ,jake-yellow)))
   `(lsp-ui-peek-peek ((t :background unspecified :foreground unspecified)))
   `(lsp-ui-peek-selection ((t :inherit (hl-line jake-yellow-glow) :background unspecified :foreground unspecified)))
   `(magit-branch-local ((t :inherit jake-yellow-glow :foreground unspecified :background unspecified)))
   `(magit-branch-remote ((t :inherit jake-green-glow :foreground unspecified :background unspecified)))
   `(magit-diff-hunk-heading ((t (:inherit jake-purple-subtle-glow :foreground ,jake-purple-subtle :background ,jake-dark :underline t))))
   `(magit-diff-hunk-heading-highlight ((t (:inherit jake-purple-glow :foreground unspecified :background ,jake-dark :underline t))))
   `(magit-section-highlight ((t :inherit jake-highlight :background unspecified)))
   `(match ((t :inherit (jake-green-glow bold) :background unspecified :foreground unspecified)))
   `(minibuffer-prompt ((t (:foreground ,jake-yellow :inherit (bold)))))
   `(mode-line ((t (:box (:line-width (1 . 1) :color ,jake-purple :style nil) :overline nil :inherit jake-yellow-glow :foreground unspecified :background ,jake-purple-dark))))
   `(mode-line-buffer-id ((t (:foreground "#bc6ec5" :inherit (bold)))))
   `(mode-line-emphasis ((t (:inherit bold))))
   `(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (jake-highlight)))))
   `(mode-line-inactive ((t (:weight light :box (:line-width (1 . 1) :color ,jake-purple-subtle :style nil) :inherit jake-purple-subtle-glow :foreground unspecified :background ,jake-dark))))
   `(mu4e-flagged-face ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(mu4e-header-face ((t (:foreground ,jake-purple))))
   `(mu4e-header-highlight-face ((t (:inherit jake-highlight :background unspecified))))
   `(mu4e-header-key-face ((t (:inherit jake-yellow-glow :foreground unspecified))))
   `(mu4e-header-title-face ((t (:inherit jake-purple-glow :foreground unspecified))))
   `(mu4e-highlight-face ((t (:inherit (jake-pink-glow bold) :foreground unspecified))))
   `(mu4e-related-face ((t (:inherit (mu4e-header-face)))))
   `(mu4e-replied-face ((t (:inherit (mu4e-header-face) :foreground ,jake-purple))))
   `(mu4e-title-face ((t (:inherit jake-green-glow :foreground unspecified))))
   `(mu4e-unread-face ((t (:inherit jake-yellow-glow :foreground unspecified :weight ,jake-normal-weight))))
   `(next-error ((t (:weight normal :inherit (error)))))
   `(orderless-match-face-0 ((t :inherit jake-green-glow :foreground unspecified :weight ,jake-normal-weight)))
   `(orderless-match-face-1 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(orderless-match-face-2 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(orderless-match-face-3 ((t :inherit orderless-match-face-0 :foreground unspecified)))
   `(org-agenda-calendar-event ((t (:inherit org-agenda-done :foreground unspecified))))
   `(org-agenda-date ((t (:inherit (jake-script jake-purple) :height 1.2 :foreground unspecified))))
   `(org-agenda-date-today ((t (:inherit (jake-yellow-glow org-agenda-date) :foreground unspecified))))
   `(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground unspecified))))
   `(org-agenda-date-weekend-today ((t (:inherit org-agenda-date-today :foreground unspecified))))
   `(org-agenda-done ((t (:inherit jake-script :foreground ,jake-purple-subtle :strike-through t))))
   `(org-agenda-structure ((t (:inherit (jake-script jake-pink-glow) :height 1.5 :foreground unspecified))))
   `(org-block ((t (:inherit (fixed-pitch) :background ,jake-purple-dark :height 0.8 ))))
   `(org-block-begin-line ((t (:inherit (fixed-pitch jake-purple-subtle-glow) :foreground unspecified :background ,jake-purple-dark))))
   `(org-block-end-line ((t (:inherit (fixed-pitch) :foreground ,jake-purple-subtle :background ,jake-purple-dark))))
   `(org-checkbox ((t (:inherit jake-green-glow :family ,jake-fixed :foreground unspecified))))
   `(org-checkbox-statistics-done ((t (:inherit (fixed-pitch) :foreground ,jake-green))))
   `(org-checkbox-statistics-todo ((t (:inherit (fixed-pitch) :foreground ,jake-pink))))
   `(org-code ((t (:inherit (fixed-pitch) :background ,jake-purple-dark :foreground ,jake-pink))))
   `(org-date ((t (:inherit (jake-script jake-purple-subtle) :foreground unspecified :underline unspecified))))
   `(org-date-selected ((t (:foreground ,jake-dark :background ,jake-yellow))))
   `(org-done ((t (:inherit jake-green-glow :background unspecified :foreground unspecified :family ,jake-script :height 0.75 :weight thin))))
   `(org-drawer ((t (:inherit (jake-script jake-purple-subtle) :background unspecified :foreground unspecified))))
   `(org-ellipsis ((t (:inherit jake-green-glow :foreground unspecified))))
   `(org-indent ((t (:inherit (org-hide fixed-pitch)))))
   `(org-journal-calendar-entry-face ((t (:foreground unspecified))))
   `(org-level-1 ((t (:family ,jake-variable-heading :inherit jake-pink-glow :foreground unspecified :height 2.0))))
   `(org-level-2 ((t (:family ,jake-variable :foreground ,jake-org-2 :height 1.5))))
   `(org-level-3 ((t (:family ,jake-variable :foreground ,jake-org-3 :height 1.25))))
   `(org-level-4 ((t (:family ,jake-variable :foreground ,jake-org-4 :height 1.1))))
   `(org-level-5 ((t (:family ,jake-variable :foreground ,jake-org-5 :height 1.1))))
   `(org-level-6 ((t (:family ,jake-variable :foreground ,jake-org-6 :height 1.1))))
   `(org-level-7 ((t (:family ,jake-variable :foreground ,jake-org-7 :height 1.1))))
   `(org-level-8 ((t (:family ,jake-variable :foreground ,jake-org-8 :height 1.1))))
   `(org-link ((t (:inherit (jake-cyan-highlight-glow) :foreground unspecified :underline unspecified))))
   `(org-meta-line ((t (:inherit (fixed-pitch) :foreground ,jake-purple-subtle :background unspecified))))
   `(org-priority ((t (:inherit (jake-script jake-purple) :foreground unspecified :height 0.75 :weight ,jake-normal-weight))))
   `(org-scheduled ((t (:inherit jake-script :foreground ,jake-cyan :slant unspecified))))
   `(org-scheduled-previously ((t (:inherit jake-script :foreground ,jake-purple-subtle :slant unspecified))))
   `(org-scheduled-today ((t (:inherit jake-script :foreground ,jake-green :slant unspecified))))
   `(org-special-keyword ((t (:inherit jake-purple-subtle :foreground unspecified :family ,jake-script))))
   `(org-superstar-item ((t (:inherit (fixed-pitch) :foreground ,jake-pink))))
   `(org-superstar-leading ((t (:inherit (fixed-pitch) :foreground ,jake-dark))))
   `(org-table ((t (:inherit (fixed-pitch) :foreground ,jake-pink :background ,jake-purple-dark))))
   `(org-tag ((t (:inherit (jake-script jake-purple-subtle) :foreground unspecified :height 0.75 :weight ,jake-normal-weight))))
   `(org-todo ((t (:inherit jake-pink-glow :background unspecified :foreground unspecified :family ,jake-script :height 0.75 :weight thin))))
   `(org-verbatim ((t (:inherit (fixed-pitch jake-yellow-glow) :foreground unspecified :background ,jake-purple-dark :weight ,jake-normal-weight))))
   `(origami-fold-header-face ((t)))
   `(query-replace ((t (:inherit (isearch)))))
   `(rainbow-delimiters-depth-1-face ((t (:inherit (jake-pink) :foreground unspecified))))
   `(rainbow-delimiters-depth-2-face ((t (:inherit (jake-yellow) :foreground unspecified))))
   `(rainbow-delimiters-depth-3-face ((t (:inherit (jake-green) :foreground unspecified))))
   `(rainbow-delimiters-depth-4-face ((t (:inherit (jake-cyan) :foreground unspecified))))
   `(rainbow-delimiters-depth-5-face ((t (:inherit (jake-purple) :foreground unspecified))))
   `(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-depth-1-face :foreground unspecified))))
   `(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-depth-2-face :foreground unspecified))))
   `(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-depth-3-face :foreground unspecified))))
   `(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-depth-4-face :foreground unspecified))))
   `(region ((t (:inherit jake-no-glow :foreground ,jake-purple-dark :background ,jake-yellow))))
   `(secondary-selection ((t (:extend t :background "#100a14"))))
   `(shadow ((t (:foreground "#494685"))))
   `(show-paren-match ((t (:foreground unspecified))))
   `(sp-show-pair-match-face ((t (:foreground unspecified))))
   `(term ((t (:inherit default :foreground ,jake-cyan :background ,jake-dark :weight unspecified))))
   `(term-color-white ((t (:foreground ,jake-cyan :background ,jake-cyan))))
   `(term-color-black ((t (:foreground ,jake-dark :background ,jake-dark))))
   `(term-color-bright-black ((t (:foreground ,jake-purple-subtle :background ,jake-purple-subtle))))
   `(term-color-blue ((t (:foreground ,jake-purple :background ,jake-purple))))
   `(term-color-bright-blue ((t (:inherit (term-color-blue bold) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(term-color-bright-green ((t (:inherit (term-color-green bold) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(term-color-bright-yellow ((t (:inherit (bold term-color-yellow) :foreground unspecified :background unspecified :weight unspecified))))
   `(term-color-red ((t (:inherit jake-pink-glow :foreground unspecified :background ,jake-pink))))
   `(tide-hl-identifier-face ((t (:foreground unspecified :background ,jake-purple-dark))))
   `(tooltip ((t (:inherit (jake-pink-glow jake-script) :foreground ,jake-pink :background ,jake-purple-dark))))
   `(trailing-whitespace ((t (:background "#2aa1ae"))))
   `(transient-argument ((t (:inherit jake-green-glow))))
   `(transient-inactive-argument ((t (:inherit jake-purple-glow :foreground unspecified))))
   `(transient-posframe ((t :background ,jake-purple-dark)))
   `(transient-posframe-border ((t :background ,jake-yellow)))
   `(variable-pitch ((t (:family ,jake-variable :height 1.3 :weight light))))
   `(vertical-border ((t (:foreground "#4a1e64"))))
   `(vertico-current ((t (:inherit jake-highlight))))
   `(vertico-group-separator ((t :inherit (jake-script jake-pink-glow) :foreground unspecified :background unspecified :underline ,jake-pink)))
   `(vertico-group-title ((t :inherit (jake-script jake-pink-glow) :foreground unspecified :background unspecified :underline ,jake-pink)))
   `(vterm-color-black ((t (:foreground ,jake-dark :background ,jake-dark))))
   `(vterm-color-blue ((t (:foreground ,jake-purple :background ,jake-purple))))
   `(vterm-color-green ((t (:foreground ,jake-green :background ,jake-green))))
   `(vterm-color-red ((t (:foreground ,jake-pink :background ,jake-pink))))
   `(vterm-color-yellow ((t (:foreground ,jake-yellow :background ,jake-yellow))))
   `(warning ((t (:inherit jake-yellow :foreground unspecified))))
   `(web-mode-html-attr-equal-face ((t (:inherit (jake-pink-glow bold) :foreground unspecified))))
   `(web-mode-html-attr-name-face ((t (:inherit jake-purple-glow :foreground unspecified))))
   `(web-mode-html-attr-value-face ((t :inherit jake-green-glow :foreground unspecified)))
   `(web-mode-html-tag-bracket-face ((t (:inherit (jake-pink-glow bold) :foreground unspecified))))
   `(web-mode-html-tag-face ((t (:inherit (jake-yellow-glow) :foreground unspecified))))
   `(web-mode-keyword-face ((t (:inherit (font-lock-keyword-face) :foreground unspecified))))
   `(web-mode-string-face ((t (:inherit (font-lock-string-face) :foreground unspecified))))
   `(web-mode-symbol-face ((t (:inherit font-lock-constant-face :foreground unspecified))))
   `(web-mode-variable-name-face ((t :foreground unspecified)))
   `(which-key-command-description-face ((t :inherit jake-cyan :foreground unspecified)))
   `(which-key-group-description-face ((t :inherit jake-yellow-glow :foreground unspecified)))
   `(which-key-key-face ((t :inherit (jake-pink-glow bold) :foreground unspecified)))
   `(which-key-posframe ((t :background ,jake-purple-dark)))
   `(which-key-posframe-border ((t :background ,jake-yellow)))
   `(which-key-separator-face ((t :inherit jake-green-glow :foreground unspecified)))
   `(widget-button ((t :inherit bold :weight unspecified)))
   ))

(setq xterm-color-names
      (vconcat (list jake-darkest jake-pink jake-green jake-yellow jake-purple jake-purple jake-cyan jake-cyan)))
(setq xterm-color-names-bright
      (vconcat (list jake-purple-subtle jake-pink jake-green jake-yellow jake-purple jake-purple jake-cyan jake-cyan)))

(set-face-attribute 'jake-no-glow nil :shadow nil)
(set-face-attribute 'jake-cyan nil :shadow nil)
(set-face-attribute 'jake-green nil :shadow nil)
(set-face-attribute 'jake-pink nil :shadow nil)
(set-face-attribute 'jake-purple nil :shadow nil)
(set-face-attribute 'jake-purple-subtle nil :shadow nil)
(set-face-attribute 'jake-yellow nil :shadow nil)

(set-face-attribute 'jake-cyan-glow nil :shadow `(10.0 ,jake-cyan 0 . 0))
(set-face-attribute 'jake-cyan-highlight-glow nil :shadow `(10.0 ,jake-cyan-highlight 0 . 0))
(set-face-attribute 'jake-green-glow nil :shadow `(10.0 ,jake-green 0 . 0))
(set-face-attribute 'jake-pink-glow nil :shadow `(10.0 ,jake-pink 0 . 0))
(set-face-attribute 'jake-purple-glow nil :shadow `(10.0 ,jake-purple 0 . 0))
(set-face-attribute 'jake-purple-subtle-glow nil :shadow `(5.0 ,jake-purple-subtle 0 . 0))
(set-face-attribute 'jake-yellow-glow nil :shadow `(10.0 ,jake-yellow 0 . 0))
(set-face-attribute 'line-number nil :shadow '(10.0 "#4A1E64" 0 . 0))
(set-face-attribute 'line-number-current-line nil :shadow '(10.0 "#7912ce" 0 . 0))

(set-face-attribute 'nerd-icons-blue nil :shadow nil)
(set-face-attribute 'nerd-icons-blue-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-cyan nil :shadow nil)
(set-face-attribute 'nerd-icons-cyan-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-dblue nil :shadow nil)
(set-face-attribute 'nerd-icons-dcyan nil :shadow nil)
(set-face-attribute 'nerd-icons-dgreen nil :shadow nil)
(set-face-attribute 'nerd-icons-dmaroon nil :shadow nil)
(set-face-attribute 'nerd-icons-dorange nil :shadow nil)
(set-face-attribute 'nerd-icons-dpink nil :shadow nil)
(set-face-attribute 'nerd-icons-dpurple nil :shadow nil)
(set-face-attribute 'nerd-icons-dred nil :shadow nil)
(set-face-attribute 'nerd-icons-dsilver nil :shadow nil)
(set-face-attribute 'nerd-icons-dyellow nil :shadow nil)
(set-face-attribute 'nerd-icons-green nil :shadow nil)
(set-face-attribute 'nerd-icons-lblue nil :shadow nil)
(set-face-attribute 'nerd-icons-lcyan nil :shadow nil)
(set-face-attribute 'nerd-icons-lgreen nil :shadow nil)
(set-face-attribute 'nerd-icons-lmaroon nil :shadow nil)
(set-face-attribute 'nerd-icons-lorange nil :shadow nil)
(set-face-attribute 'nerd-icons-lpink nil :shadow nil)
(set-face-attribute 'nerd-icons-lpurple nil :shadow nil)
(set-face-attribute 'nerd-icons-lred nil :shadow nil)
(set-face-attribute 'nerd-icons-lsilver nil :shadow nil)
(set-face-attribute 'nerd-icons-lyellow nil :shadow nil)
(set-face-attribute 'nerd-icons-maroon nil :shadow nil)
(set-face-attribute 'nerd-icons-orange nil :shadow nil)
(set-face-attribute 'nerd-icons-pink nil :shadow nil)
(set-face-attribute 'nerd-icons-purple nil :shadow nil)
(set-face-attribute 'nerd-icons-purple-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-red nil :shadow nil)
(set-face-attribute 'nerd-icons-red-alt nil :shadow nil)
(set-face-attribute 'nerd-icons-silver nil :shadow nil)
(set-face-attribute 'nerd-icons-yellow nil :shadow nil)

(provide-theme 'omarchy)
